### ISSUE TITLE
cvmfs-contrib unavailable for ubuntu?

### ISSUE THREAD

**Issue by astroclark** [cvmfs-contrib/cvmfs-x509-helper#12]
The cvmfs-contrib repository appears to be unavailable for Ubuntu, although I am able to install `cvmfs-x509-helper` in Ubuntu using the Debian 9 cvmfs-contrib repository by replacing the symlink to the ubuntu repo with one to the debian repo:

Try to install cvmfs-x509-helper:
```
➜  ~ apt install cvmfs-x509-helper
<snip>
The following packages have unmet dependencies: cvmfs-x509-helper : Depends: libvomsapi1 but it is not installable
```

Now follow instructions at https://cvmfs-contrib.github.io/ to enable cvmfs-contrib repositories.  Updating apt gives:
```
N: Ignoring 'cvmfs-contrib.list' in directory '/etc/apt/sources.list.d/' as it is not a regular file
```
Because the symlink:
```
/etc/apt/sources.list.d/cvmfs-contrib.list -> /usr/share/cvmfs-contrib-release/cvmfs-contrib-Ubuntu_18.04.list
```
points to a non-existent file
```
ls /usr/share/cvmfs-contrib-release/
cvmfs-contrib-Debian_8.0.list  cvmfs-contrib-Ubuntu_14.04.list  cvmfs-contrib-Ubuntu_17.04.list
cvmfs-contrib-Debian_9.0.list  cvmfs-contrib-Ubuntu_16.04.list
```
Further, the URLs for the other Ubuntu releases give a 404 error.  

Replacing the symlink to the non-existent Ubuntu repository with a link to the Debian 9 repository allows me to install, and use, cvmfs-x509-helper just fine.

--

**Comment by DrDaveD** [comment]
@astroclark This is an issue with the cvmfs-contrib-release package, could you submit your issue there instead?

**Comment by astroclark** [comment]
done, closing
